/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import classes.Board;
import java.awt.Font;

/**
 *
 * @author viribusegovis
 */
public class Tetris extends javax.swing.JFrame {

    Board board;

    private MainMenu originalInstance;

    /**
     * Creates new form Tetris
     */
    public Tetris() {
        initComponents();
    }

    public Tetris(MainMenu originalInstance) {
        initComponents();
        board = new Board(20, 10);
        txtGame.setText(board.toString());
        this.originalInstance = originalInstance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnLeft1 = new javax.swing.JButton();
        btnDown1 = new javax.swing.JButton();
        btnRight1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        spnColls = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        spnLines = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnFall1 = new javax.swing.JButton();
        btnRotate1 = new javax.swing.JButton();
        menuButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGame = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel4ComponentResized(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(new java.awt.GridLayout(1, 3));

        btnLeft1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLeft1.setText("◄");
        btnLeft1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeft1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnLeft1);

        btnDown1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDown1.setText("▼");
        btnDown1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDown1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnDown1);

        btnRight1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRight1.setText("►");
        btnRight1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRight1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnRight1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel6.setLayout(new java.awt.GridLayout());

        jPanel7.setLayout(new java.awt.BorderLayout());

        spnColls.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spnCollsKeyReleased(evt);
            }
        });
        jPanel7.add(spnColls, java.awt.BorderLayout.CENTER);

        jLabel3.setText("Collumns:  ");
        jPanel7.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jPanel6.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());

        spnLines.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spnLinesKeyReleased(evt);
            }
        });
        jPanel8.add(spnLines, java.awt.BorderLayout.CENTER);

        jLabel2.setText("Lines:  ");
        jPanel8.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel6.add(jPanel8);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.setLayout(new java.awt.GridLayout());

        btnFall1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFall1.setText("FALL");
        btnFall1.setMinimumSize(new java.awt.Dimension(27, 27));
        btnFall1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFall1ActionPerformed(evt);
            }
        });
        jPanel9.add(btnFall1);

        btnRotate1.setText("↻");
        btnRotate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotate1ActionPerformed(evt);
            }
        });
        jPanel9.add(btnRotate1);

        menuButton1.setText("Back to Menu");
        menuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(menuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4);

        txtGame.setEditable(false);
        txtGame.setColumns(20);
        txtGame.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 14)); // NOI18N
        txtGame.setRows(5);
        txtGame.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txtGameComponentResized(evt);
            }
        });
        jScrollPane1.setViewportView(txtGame);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeft1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeft1ActionPerformed
        board.moveLeft();
        txtGame.setText(board.toString());
    }//GEN-LAST:event_btnLeft1ActionPerformed

    private void btnDown1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDown1ActionPerformed
        board.moveDown();
        txtGame.setText(board.toString());
    }//GEN-LAST:event_btnDown1ActionPerformed

    private void btnRight1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRight1ActionPerformed
        board.moveRight();
        txtGame.setText(board.toString());
    }//GEN-LAST:event_btnRight1ActionPerformed

    private void spnCollsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnCollsKeyReleased
        System.out.println("spnColls, Event, Key Release");
        board = new Board((int)spnColls.getValue(),10);
        txtGame.setText(board.toString());
    }//GEN-LAST:event_spnCollsKeyReleased

    private void spnLinesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnLinesKeyReleased
        System.out.println("spnColls, Event, Key Release");
        board = new Board((int)spnColls.getValue(),10);
    }//GEN-LAST:event_spnLinesKeyReleased

    private void btnFall1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFall1ActionPerformed
        board.fallDown();
        txtGame.setText(board.toString());
    }//GEN-LAST:event_btnFall1ActionPerformed

    private void btnRotate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotate1ActionPerformed
        board.rotate();
        txtGame.setText(board.toString());
    }//GEN-LAST:event_btnRotate1ActionPerformed

    private void menuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButton1ActionPerformed
        originalInstance.setVisible(true); // Make the original instance visible again
        dispose(); // Close the current window
    }//GEN-LAST:event_menuButton1ActionPerformed

    private void jPanel4ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel4ComponentResized
    }//GEN-LAST:event_jPanel4ComponentResized
    
    private void txtGameComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtGameComponentResized
        int width = txtGame.getWidth();
            txtGame.setFont(new Font("DejaVu Sans Mono", Font.BOLD , width / 21));
            txtGame.revalidate();
    }//GEN-LAST:event_txtGameComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tetris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tetris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tetris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tetris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tetris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDown1;
    private javax.swing.JButton btnFall1;
    private javax.swing.JButton btnLeft1;
    private javax.swing.JButton btnRight1;
    private javax.swing.JButton btnRotate1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menuButton1;
    private javax.swing.JSpinner spnColls;
    private javax.swing.JSpinner spnLines;
    private javax.swing.JTextArea txtGame;
    // End of variables declaration//GEN-END:variables
}
